### ISSUE TITLE
Enhance custom_id creation in batch functions

### ISSUE THREAD

**Issue by JiaZhang42** [edubruell/tidyllm#37]
Hi Eduard,

I noticed that both OpenAI and Anthropic batch APIs don't guarantee the order when returning the results, causing problems to codes such as 
```
occ2_codes <- read_rds("sub_sample_batch.rds")) |>
  fetch_claude_batch() |>
  map_chr(get_reply) |>
  parse_number()

tibble(occupation_open = sub_sample$occupation,
       occ2 = occ2_codes) |>
  left_join(occ_codes, by="occ2") |>
  writexl::write_xlsx("ground_truth_excel.xlsx")
```
in the article [Classifying Texts with tidyllm](https://edubruell.github.io/tidyllm/articles/tidyllm_classifiers.html). Of course one can manually name the list when creating the llm messages, but this is so easily ignored. Do you think it is a good idea to add request IDs as a required parameter of the batch functions or create IDs implicitly and sort results based on the implicit IDs? Thanks!

**Comment by edubruell** [comment]
Oh I did not notice this one yet and I am not sure I fully understand what you mean. Does claude or openai return the wrong results with an ID name? For send batch functions I typically have something like this where implicit names are generated, which should ensure that ids are created for each LLMMessage if names are missing. 

```r
    custom_id <- names(.llms)[i]
    if (is.null(custom_id) || custom_id == "" || is.na(custom_id)) {
      custom_id <- paste0(.id_prefix, i)  # Generate a custom ID if name is missing
      names(.llms)[i] <<- custom_id  # Assign generated ID as the name of .llms
    }
```
And this here in the fetch_batch functions: 

```r
  results_by_custom_id <- purrr::set_names(results_list, sapply(results_list, function(x) x$custom_id))
  updated_llms <- lapply(names(.llms), function(custom_id) {
    result <- results_by_custom_id[[custom_id]]
    
    if (!is.null(result) && result$result$type == "succeeded") {
      assistant_reply <- result$result$message$content$text
      llm <- add_message(llm = .llms[[custom_id]],
                         role = "assistant", 
                         content = assistant_reply,
                         meta = extract_response_metadata(result$result$message))
      return(llm)
    } else {
      warning(sprintf("Result for custom_id %s was unsuccessful or not found", custom_id))
      return(.llms[[custom_id]])
    }
  })
```
I am wondering what's causing the error? Do you have an example for a batch that was stitched together wrong?  By the way, do you want to add yourself as contributor to the DESCRIPTION file?

**Comment by edubruell** [comment]
Or is it just the sort order for fetch_batch(). Perhaps this would need a way to preserve the sort-order for batches, when they are send by saving it somewhere in the batch.

**Comment by JiaZhang42** [comment]
Thanks!
